// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nav-logo/Current.tsx": () => import("../components/mockups/nav-logo/Current.tsx"),
  "./components/mockups/nav-logo/WithName.tsx": () => import("../components/mockups/nav-logo/WithName.tsx"),
  "./components/mockups/nav-logo/WithTagline.tsx": () => import("../components/mockups/nav-logo/WithTagline.tsx")
};
